### ISSUE TITLE
Decide on CMS (if any)

### ISSUE THREAD

**Issue by DainialPadraig** [CodeForTucson/tucson-green-living#2]
Should this project use a CMS? If so, which one?

Need to create a comparison table of pros/cons for various options and choose one.

**Comment by gnublet** [comment]
| Technology  | Type | Pros | Cons |
| --------  | ---- | ------------------- | --------------------- |
| Wordpress | Traditional CMS | Our prototype uses this, Easy to use, lots of extensions | Maintaining a database costs money, Tends to have lots of bugs and security issues                | 
| Drupal | Traditional CMS | Moderate ease of use, very flexible if you want advanced features | Maintaining a database costs money, harder to learn than Wordpress, upgrade process can be a huge pain especially from 6/7->8/9/10, documentation is very poor
| Eleventy | Jamstack | Free, Up and coming framework, flexible, allows API calls and partial hydration, planned to be used in codefortucson's home page | Not as straight forward as other Jamstack frameworks, especially when you need javascript |
| Astro | Jamstack | Free, Up and coming framework, flexible, allows API calls and partial hydration, can mix and match from different javascript frameworks | Slightly less popular 
| Hugo | Jamstack | Free, fast build times, easy to use | not as flexible as some more modern frameworks, not as easy to use with javascript or API calls |
| Jekyll | Jamstack | Free, lots of documentation | uses Ruby (which is slow and losing popularity), has less features than modern frameworks |

**Comment by gnublet** [comment]
If git is too complicated, we can use NetlifyCMS along with a static site generator listed above to handle the content side of things

**Comment by gnublet** [comment]
We'll use NetlifyCMS for ease of use for content management and NuxtJS for flexibility

**Comment by gnublet** [comment]
I'll probably switch from NuxtJS to Astro. The reason is that even though NuxtJS universal mode claims to be SEO friendly, it's possible that not all SEO crawlers index javascript pages correctly which would cause them to miss important content used for indexing. Another advantage is that Astro supports multiple front-end frameworks, not just Vue. 

For example, Bing (as of 2018) indexes javascript pages, but is not always reliable: https://www.screamingfrog.co.uk/bing-javascript/ . Since the whole point of this project is to make sustainability widely accessible, the risk of sticking with a javascript based app is too much.
